### ISSUE TITLE
Crop unification

### ISSUE THREAD

**Issue by Sunconure11** [AlmostReliable/almostunified#10]
### Describe the feature/addition!

The drops from various crops, as well as some crops themselves, should be unified under this mod

### Why would like to see this feature/addition?

When having a decent-sized pack, you are bound to run into duplicate crops. This can also make crafting with them more difficult.

**Comment by rlnt** [comment]
Could you elaborate a bit on that topic? Or maybe give a precise example of what your understanding of "Crop unification" is?

If you have multiple flax crops, for example, do you want all of them to drop the same flax seed and flax item? That is possible already. If the items share tags, you can add them to your `unify.json` config. Otherwise, you have to add the tags yourself and add the custom tags to the config.
After that, you can edit the loot table of the crops to drop the preferred items by using [LootJS](https://github.com/AlmostReliable/lootjs) and the KubeJS binding we expose. From experiences in the past, not all mods make use of loot tables properly so that won't work with all crops but there is nothing we can do about it.

**Comment by Sunconure11** [comment]
I want them to all share tags as well as be usable in all of the same recipes. But otherwise, you got it right, yeah

**Comment by rlnt** [comment]
I am sorry but there is no magic way of doing that. If you want unified drops, you have to do that yourself by the aforementioned steps. Not all crop drops are tagged properly and we can't do that for every mod. That's up to the pack devs. After tagging the drops, you can just add the new tags to the config and they will be automatically unified.

**Comment by Sunconure11** [comment]
I seem to be figuring crops out, but what would be a good way of going about meat? Like say, you have several mods adding deer with venison for instance.

**Comment by rlnt** [comment]
Please join our [Discord](https://discord.com/invite/ThFnwZCyYY) for support requests and for help setting up the mod properly. This is not a feature request. Thanks :)
