### ISSUE TITLE
There is some incompatibility with TerraFirmaCraft: The Next Generation

### ISSUE THREAD

**Issue by xiaojuzi122** [AlmostReliable/almostunified#107]
### Minecraft Version

1.20.1

### Mod Version

1.20.1-0.9.4

### Describe the bug!

When a mineral block in TerraFirmaCraft drops, it should fall into a low-quality block, such as enriched copper turning into normal copper, and ordinary copper turning into barren copper.
However, when Almost Unified is installed, regular copper will become the original Minecraft Copper Ore
Adjusted the Almost Unified profile so that TerraFirmaCraft has the highest priority, but Normal Copper drops to Enriched Copper
This is also the case with gold mines and Create's zinc mines
![无标题视频——使用Clipchamp制作](https://github.com/user-attachments/assets/f9ad0278-47e8-4e33-9643-e20919e7d221)
![无标题视频——使用Clipchamp制作 (1)](https://github.com/user-attachments/assets/101c3b86-8d6d-40dc-b321-c7a9a847c56a)

### Additions and Modifications

Yes

### Additions and Modifications Description

Create, Immersive Engineering, and TerraFirmaCraft: The Next Generation installed

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
I am not sure if I understand the issue correctly. I don't have any experience with TFC, but generally, this is not a mod issue but a configuration issue. Please join the Discord for support instead.

I assume TFC handles this system using a recipe. Otherwise, I would be confused about why this happens because Almost Unified for 1.20 only touches recipes.
