### ISSUE TITLE
Config option to disable unified icon in JEI/REI

### ISSUE THREAD

**Issue by Nevrai** [AlmostReliable/almostunified#12]
### Describe the feature/addition!

I love the mod quite a lot, but I couldn’t find a way to disable this icon in any of Almost Unified’s config files:
![EiqtMbV](https://user-images.githubusercontent.com/59761487/192706390-36c9304d-932b-44b9-a20a-8d08452c3b99.png)

I would very much like to turn this off. It appears on a lot of recipes, even vanilla ones, such as gold block, gold nugget, and gold ingot recipes, to name a few. It’d be nice to be able to disable this. Could this feature be added (to 1.18.2)? It would be much appreciated!

### Why would like to see this feature/addition?

I feel as though the icon is distracting and unnecessary.

**Comment by rlnt** [comment]
This was discussed in Discord already but just to make this clear for the future in an in-depth response and as a reference for people with the same idea.

We **won't** implement an option to disable the icon! And that's our final say. Don't take this personally; We don't want to sound rude here.

I understand that pack-makers want to have the recipe overview as clean as possible and I assume some devs might even want to hide the fact that all the unification work was done by a mod and not by them. But our priority and the main reason this icon was implemented is to avoid drama.

When a recipe causes conflicts or issues, 99% of the time this is due to the odd combination of mods, a mistake by the pack-dev, or by Almost Unified. And to make it clearly visible that we modified a recipe, we decided to have this icon. We want to avoid recipe issues being reported to the original authors. That would shine a bad light on our mod and similar scenarios caused a lot of discussions and fights in the modder scene in the past.

Even mods like KubeJS or CraftTweaker which are used to add or modify recipes generate a dynamic recipe ID to make sure recipe modifications are not reported to the original authors. But since a lot of mod compatibility relies on recipe IDs, that is not an option for us. We used this approach in the past and it caused conflicts with guidebooks that display recipes. The icon is a nice little alternative.

This is such a small icon and we made sure it does not interfere with other elements in the recipe lookup system. In our opinion, a small indicator like that shouldn't bother anyone and if it really annoys you (not speaking to you personally), feel free to remove the mod or use the serverside-only option that was introduced in v0.1.1. Avoiding unnecessary conflicts is much more valuable to us than a few downloads.

About the unification of vanilla recipes:<br>
Minecraft itself doesn't use tags for its recipes because they simply don't have to. There is only one gold, one iron, and one copper. The usage of tags wouldn't make sense for them. However, in a modded ecosystem such as a huge mod pack, it makes sense to also unify vanilla recipes as there are plenty of mods that make use of those tags and if the vanilla recipes were not unified, those mod resources would become useless.

If you want to avoid vanilla recipes being touched by the unification, feel free to add the respective tag or the specific recipe IDs to the ignore list inside AU's configs.
