### ISSUE TITLE
Recipes allow for the use of blocks of copper and cut copper interchangably 

### ISSUE THREAD

**Issue by Halex000** [AlmostReliable/almostunified#37]
### Version

0.3.5

### Describe the bug!

What I said in the title, the game treats cut copper and blocks of copper as the same thing. A stonecutter lets you cut one cut copper into 4 cut copper along with other oddities like crafting a cut copper using the recipe for a block of copper.
![Capture](https://user-images.githubusercontent.com/95841600/226094475-dc18a760-c6b4-475b-acf9-cdce931d9539.PNG)

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
Not a bug introduced by Almost Unified.

You likely have a mod that adds the copper storage block tag to the Cut Copper block. Forge did this in the past but it was quickly removed in the next version because it was not intentional. Some mods then decided to add it back for some reason.

Known mods that add the tag are old versions of Occultism and Chisels and Bits. This is also mentioned on our wiki here https://github.com/AlmostReliable/almostunified/wiki/Mod-Support#chisels-and-bits

Either you have to remove the tag from the Cut Copper block yourself or you remove the mod that adds it but this definitely isn't Almost Unified since we are not adding any tags ourselves. Some more info can be found on the Enigmatica repository where they ran into the same issue. You can find it here https://github.com/EnigmaticaModpacks/Enigmatica8/issues/283#issuecomment-1257269746

<blockquote><img src="https://opengraph.githubassets.com/ea367014a3a21033334b3765803332d96c3d00962309519dac78603d0a44be0a/AlmostReliable/almostunified" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/almostunified/wiki/Mod-Support">Mod Support</a></strong></div><div>A Minecraft mod to unify resources. Contribute to AlmostReliable/almostunified development by creating an account on GitHub.</div></blockquote>
