### ISSUE TITLE
1.18.2 When a mod has multiple items with a tag, almost unified reduces those items down to one item

### ISSUE THREAD

**Issue by radiomike** [AlmostReliable/almostunified#41]
### Version

0.3.7

### Describe the bug!

When a mod has multiple items with the same tag, almostunified reduces those items down to one item, when it should probably keep all items of the highest priority mod, which have that tag. 

This behaviour seems to have changed sometime between 0.3.3 and 0.3.7.

Noticed in the atm gravitas pack with terrafirmacraft, which adds `forge:ores/{material}` tags to its rich,normal and poor ores as well as multiple stone types of those. Prior versions (0.3.3) would keep all tfc versions. With almostunified 0.3.7 only one version of those ores exists, which breaks other functionality in the mod.

### Additional Context

Yes

### Modifications

Tested with terrafirmacraft 2.2.15

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
The new version actually fixed some edge case behavior in our automatic hiding implementation so it's working correctly now.

The issue you are facing is related to a config issue on your side. I downloaded the pack to test if I can fix the problem on the current version of AU and it's enough to add the correct ore tags.

Instead of `forge:ores/{material}` in your unify tags, you should use the different TFC variants like this:
```
"tfc:ores/{material}/poor",
"tfc:ores/{material}/normal",
"tfc:ores/{material}/rich",
```

That way, all ores will be visible again. There is only one thing left that I am not sure about since I don't know a lot about the pack. Since the normal forge ore tags are not handled anymore, the Beyond Earth ores become visible again. If you want to keep them, it's fine like that. Otherwise, you could define some tag ownerships to handle those instead.

E.g. by treating the BE ores like normal TFC ores.

**Comment by rlnt** [comment]
This was fixed on the ATM repository, closing it as AU seems to work like intended.
