### ISSUE TITLE
Game won't start - says JEI is required

### ISSUE THREAD

**Issue by Aetrnl94** [AlmostReliable/almostunified#48]
### Version

AlmostUnified-Forge-1.19.4-0.4.4

### Describe the bug!

Game crashes on trying to load an existing save or create a new game. I can't figure out what the issues is (though I'm guessing it has to do with a mod conflict). Any support would be helpful! I have REI installed (not JEI).

### Crash Report

https://gist.github.com/Aetrnl94/de1dd3200f8d43691135ea7ecc06b596

### Log

https://gist.github.com/Aetrnl94/8f280c16f9a116ecca57d8f5ff45c1ae

### Additional Context

Yes

### Modifications

I have a ton of mods that work perfectly together-- unless this mod is installed.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
The log you linked is a shader crash and doesn't list any mods. Are you sure you provided the correct links?

Edit:
Well anyways, there is nothing we can do. It's the REI compat layer that is automatically installed with REI. It pretends to be JEI with a certain version to be compatible with their API.

However, the REI compat layer is not available for 1.19.4 yet and CurseForge just pulls the 1.19.3 version of it which only supports an outdated API version of JEI. Almost Unified requires the newer API otherwise our integration for it won't work.

So the only solution is to wait for the author of REI to update the compat layer to JEIs new api and adjust the version number.

**Comment by rlnt** [comment]
Talked to Dan (author of REI) and what I mentioned is indeed the case. Sorry for the inconvenience but that's not on us and there is nothing we can do.
