### ISSUE TITLE
Failure to unify `forge:slag` in IE machines, when recipe comes from JAOPCA

### ISSUE THREAD

**Issue by NielsPilgaard** [AlmostReliable/almostunified#5]
### Version

almostunified-forge-1.18.2-0.0.7

### Describe the bug!

Recipes created by [JAOPCA](https://www.curseforge.com/minecraft/mc-mods/jaopca) in IE machines, namely the Blast Furnace & Arc Furnace are unified incorrect, their secondary output becomes `Empty Tag: forge:slag`. Recipes not created by JAOPCA are not affected, so I'm guessing this is a timing/event order issue.

The bug is in [Enigmatica 8 2.3.0](https://www.curseforge.com/minecraft/modpacks/enigmatica8/files/3989622), it's easily reproducible by downloading that 😄 
To reproduce this issue outside E8, it's required that you add `"forge:slag"` to the tags list in the Almost Unified config `unify.json`.

![image](https://user-images.githubusercontent.com/21295394/190920690-89280c36-996b-4512-a9d6-3362ff72ebeb.png)
![image](https://user-images.githubusercontent.com/21295394/190920705-a3653c79-3c05-49bd-84ed-3483414dc219.png)
![image](https://user-images.githubusercontent.com/21295394/190920715-362cede8-e94b-4d8d-8cbe-a87ada1e646d.png)

### Log

https://gist.github.com/NielsPilgaard/7100635c4a4e433a8622f4b6a91b08a7

### Additional Context

Yes

### Modifications

Added the following to `unify.json`:

```
"forge:coal_coke",
"forge:slag"
```

Changed `modPriorities` in `unify.json`:

```json
"modPriorities": [
        "emendatusenigmatica",
        "minecraft",
        "ftbic",
        "thermal",
        "immersiveengineering",
        "mekanism",
        "kubejs",
        "pneumaticcraft",
        "create",
        "occultism",
        "industrialforegoing",
        "tconstruct",
        "botania",
        "quark",
        "pedestals",
        "refinedstorage",
        "mapperbase",
        "bloodmagic",
        "eidolon",
        "morevanillalib",
        "titanium",
        "mythicbotany",
        "undergarden",
        "byg",
        "atum",
        "betterendforge",
        "miniutilities",
        "chipped",
        "chisel",
        "voluminousenergy",
        "assemblylinemachines",
        "malum"
    ]
```

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
I can confirm this. This may take a bit to fix since there is no way for me to sort this out without debugging what's going on which is currently not possible due to IE crashing the development environment in the runtime.
Waiting for responses on this one: https://github.com/BluSunrize/ImmersiveEngineering/issues/5442

**Comment by rlnt** [comment]
Well, I hate to be the bearer of bad news but this is not an AU issue.
Just to make sure, because I could not reproduce this issue in a minimal environment, I renamed the `kubejs` folder in E8 so no scripts are loaded and it works perfectly fine.

https://user-images.githubusercontent.com/16513358/191377106-be43c1f8-9c54-4bb1-ac61-bf2d886514d7.mp4

You probably have a conflict in your pack since you still use many unification scripts. I don't have the time to find the exact thing that causes this but you should make use of the [KubeJS](https://github.com/AlmostReliable/almostunified/wiki/KubeJS) binding of AU to make sure your scripts work correctly (if they are still needed at all). I can only imagine that you accidentally replace something that you shouldn't.

I tested it in multiple environments and with different versions of AU to be on the safe side but if you come up with another result, let us know!

**Comment by NielsPilgaard** [comment]
Damn, alright, thanks for testing 👍
Just to be sure, your minimal setup had AU, IE, JAOPCA and a mod adding Silver, Nickel, Aluminum or a similar ore, right? 😁

**Comment by rlnt** [comment]
My test scenario was IE, Thermal, Mekanism, JAOPCA and AU with the slag tag in the config.

But I also downloaded E8 and only renamed the Kube folder to get rid of the scripts temporarily and it worked fine.

I was only able to reproduce the bug by downloading and starting E8 as it is.

**Comment by NielsPilgaard** [comment]
Ahh okay, thanks a ton 😊
