### ISSUE TITLE
Please support forge version 43.2.0 for 1.19.2 🥺 

### ISSUE THREAD

**Issue by raffle2** [AlmostReliable/almostunified#56]
### Describe the feature/addition!

Henlo!
I'm currently playing on 1.19.2 with forge 43.2.0 and when trying to use your latest mod version `almostunified-forge-1.19.2-0.5.0.jar` my game crashes telling me it requires a mandatory forge 43.2.10 dependency. 

I'm not even sure if its feasible for you in case you do require features from a more recent forge version but would you consider still supporting 43.2.0 on top of 43.2.10?

Thank you! <3

### Why would like to see this feature/addition?

All my other hundreds of mods still use 43.2.0 and I want to keep this great mod updated but am otherwise forced to keep using `almostunified-forge-1.19.2-0.4.4.jar` if I want to use it :(

**Comment by rlnt** [comment]
I updated a lot of the project structure and brought our build tools up to date because it solved a lot of issues we had in the past.
For some reason, I was only able to get things working with 43.2.10. We don't rely on Forge updates internally, but the build tools seem to.

Our project is configured so that our dependency versions are always automatically set as minimum versions, so even though the newer Forge version isn't required in runtime, it still asks for the newer version now, which is kind of unfortunate. But I really don't want to release a new hotfix just to downgrade the minimum Forge version.

What's stopping you from updating the version? Even if other mods don't need it, it shouldn't be a problem to update. All updates from 43.2.10 were hotfixes and don't break anything.

Otherwise, you would have to wait until I find the time to implement new features into the mod. Because then I can downgrade the minimum version again.

**Comment by raffle2** [comment]
Thank you for the answer! I didn't know that about 43.2.10. I'll try updating forge in that case and hopefully nothing will break. Either way I completely understand and thank you for the work on this great mod :)
