### ISSUE TITLE
Boon of the Earth enchantment gives wrong ores

### ISSUE THREAD

**Issue by KostromDan** [AlmostReliable/almostunified#60]
### Version

1.6.3 M-Tech

### Describe the bug!

Apotheosis Boon of the Earth enchantment gives wrong ores. For example, if mekanism has greater priority, we still can get IE ores.

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Is this some kind of drop you get when using the enchantment on a tool? Almost Unified only transforms recipes, it doesn't touch any drops.

If you want to edit loot tables so they drop the unified counterparts of items, you can do that similar to this example on the wiki: https://github.com/AlmostReliable/almostunified/wiki/Limitations#unification-of-ore-generation

Since this doesn't seem to be in the scope of the mod, I'll close this one. Let me know if this is related to a recipe somehow. If you need help to unify the drop, feel free to join the Discord and ask for help there.

<blockquote><img src="https://opengraph.githubassets.com/e2a6c3ff5f1564fff77d80f6c2b9a3f61758ca7db44c1cd5f8b309c8cde2bd0a/AlmostReliable/almostunified" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/almostunified/wiki/Limitations">Limitations</a></strong></div><div>A Minecraft mod to unify resources. Contribute to AlmostReliable/almostunified development by creating an account on GitHub.</div></blockquote>
