### ISSUE TITLE
IndustrialCraft 2 Classic support

### ISSUE THREAD

**Issue by ieris19** [AlmostReliable/almostunified#61]
### Version

0.7.0

### Describe the bug!

IC2C flies completely under AU's radar. The ores are not overridden by the script provided in the "Limitations" section of the wiki, though that is more a LootJS issue than AU's.

However, none of the recipes in the mod get modified, Industrial Diamonds are still produced even though they have the tag forge:gems/diamond, bronze is still produced as an output of IC2 machines, so on and so forth. 

The issue lies with the mod, then updating the wiki to reflect that incompatibility would be appropriate. 

### Additional Context

After asking the IC2C devs, further context was provided, and while there's a solution, it's up to users to handle it. I suggest adding it to the wiki (I'm willing to it write if needed). Further context and info at the original report in [IC2Classic#895](https://github.com/TinyModularThings/IC2Classic/issues/895)

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
As you may have seen, this is a difficult subject. IndustrialCraft has always been known for doing everything their own way and showing no insight as to why they should be compatible with other mods. Also, all mods from these authors are always closed source and All rights reserved. So I will be careful not to include any support for them. The mod is incompatible because it completely bypasses the vanilla principles for no reasonable reason, which is why we have no intention to support it. I'm sorry but you can't work with these people.

**Comment by ieris19** [comment]
I fully understand and agree with that decision. I guess adding it to the list of incompatible mods would be the sensible thing to do then?
