### ISSUE TITLE
Create & Create Deco - Zinc sheets from both mods not interchangeable

### ISSUE THREAD

**Issue by Kilior** [AlmostReliable/almostunified#65]
### Version

AlmostUnified 1.20.1-0.7.2

### Describe the bug!

The mechanical press that makes the Zinc sheet will default to make the version from Create Deco. The version from Create Deco does not work for Create Crafts & Additions recipes thus halting progression in the Create Crafts & Additions mod.

### Additional Context

Yes

### Modifications

The mod pack is called "Chosen's Modded Adventure".

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Kilior** [comment]
The Zinc Sheet from Create Crafts & Additions recipe does not say anything about being unified if that helps.

**Comment by rlnt** [comment]
That sounds like an issue you should report to the modpack author since this certainly is a configuration issue. In case you are the pack author, you can join the Discord and ask for help there.

There can be several reasons it doesn't unify these plates properly:
- one or both of these plates are not tagged correctly
- the shared tag is not contained within the unify tags
- none of the mods is on the priority list so Almost Unified doesn't know which item to pick

Either way, this is not a mod issue because you have to configure it properly to cover all cases. We can't cover everything by default.
