### ISSUE TITLE
Raw Silver Block not Unifying

### ISSUE THREAD

**Issue by ffuentesm** [AlmostReliable/almostunified#68]
### Version

almostunified-forge-1.20.1-0.8.0

### Describe the bug!

The recipes are from Occultism, Immersive Engineering, Ice and Fire

https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/main/resources/data/occultism/recipes/crafting/raw_silver_block.json
https://github.com/AlexModGuy/Ice_and_Fire/blob/1.20/src/generated/resources/data/iceandfire/recipes/raw_silver_to_raw_silver_block.json
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/generated/resources/data/immersiveengineering/recipes/crafting/raw_silver_to_raw_block_silver.json

![image](https://github.com/AlmostReliable/almostunified/assets/44974827/9adbfc0e-0063-4494-8a62-54d85fbc6c3b)

I think the problem might be Occultism using forge:raw_ore instead of forge:raw_material tag. But I and not sure if UA should or not unify both tag, as raw_ore was an older tag from forge that was replaced with raw_material

### Additional Context

Yes

### Modifications

Just a private mod list that I play with, things like Create, IE, Occutims, EMI/JEI, Ice and Fire, JAOPCA, Ars, etc.
Nothing in the technical configs was altered.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
If an issue like that exists, you can easily fix that yourself with the help of tag ownerships: https://github.com/AlmostReliable/almostunified/wiki/Unification-Config#tag-ownerships

It allows you to convert a specific tag to another. However, this should probably be fixed by the respective mod as well. I sent KliKli (author of Occultism) a message about this.

<blockquote><img src="https://opengraph.githubassets.com/d84c6946e36d6b66e529654206670a4a589ba4e2734693187acea14bdf792037/AlmostReliable/almostunified" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/almostunified/wiki/Unification-Config">Unification Config</a></strong></div><div>A Minecraft mod to unify resources. Contribute to AlmostReliable/almostunified development by creating an account on GitHub.</div></blockquote>

**Comment by klikli-dev** [comment]
This should be fixed now (see https://github.com/klikli-dev/occultism/issues/1064)
