### ISSUE TITLE
Keeps reverting my changes every reload

### ISSUE THREAD

**Issue by Melechtna** [AlmostReliable/almostunified#72]
### Minecraft Version

1.19.2

### Mod Version

0.8.1

### Describe the bug!

I remove the mods I don't have, add the ones I want, do /reload. and the json is reverted to the default for some weird reason.

### Log

https://gist.github.com/Melechtna/5db691cf1035ffa25a3cf5c1f4500e29

### Additions and Modifications

Yes

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Melechtna** [comment]
Okay, so, why EXACTLY do the defaults have to stick around in order for my additions to function? I don't use IE, Mek, thermal, or crafttweaker, so why does the script revert if I take these out?

**Comment by rlnt** [comment]
I mean it tells you the reason in the log.
```
[16Mar2024 10:48:11.415] [Worker-Main-15/WARN] [AlmostUnified/]: Config unify is invalid. Backing up and recreating.
[16Mar2024 10:48:11.416] [Worker-Main-15/WARN] [AlmostUnified/]: Creating config: unify
```
If the mod can't parse your config because it's invalid, it needs to be recreated otherwise it wouldn't have config values at all.

Try to use a JSON validator (can be found online) to ensure your config is valid after your modifications. This is not a bug.
