### ISSUE TITLE
[Feature Request] Unification of Trees

### ISSUE THREAD

**Issue by ClockworkCorvus** [AlmostReliable/almostunified#76]
### Describe the feature/addition!

So you know how many mods add the same tree types? In a large modpack you might have multiple versions of maple, redwood, or pine, for example. Well imagine if this mod could handle that by unifying the woodsets and leaves? So even in biomes from different mods, while the shapes of the trees might be different, the materials remain the same. The only downside I can see happening is that you won't be able to regrow those trees into that shape again, only the dominant one's.

### Why would like to see this feature/addition?

For me this has been a small pet peeve that has been bothering me for quite a long time, and I am certain I am not alone in saying that, so I feel like this would be a much welcomed addition.

**Comment by rlnt** [comment]
I think this is out of the scope of the main mod. If someone wants this, they can make an add-on for it. The dominant items are exposed in our API.

There currently is no world gen unification in Almost Unified. We plan to introduce some world feature altering in the 1.20.4+ version but we need to check if it's feasible first. Even if we introduce this, this will likely only cover ore removal because some mods don't have a config option to do so.

Sorry, this won't make it to the mod. But our new upcoming inventory unification system might solve the issue for you. It will unify items on pickup so when you break the non-dominant tree, it will convert to the dominant counterpart in your inventory. It will only make it to 1.20.4+ tho since we are redoing a lot of the internals there.
