### ISSUE TITLE
Tierify / Tiered reforge_material base support 

### ISSUE THREAD

**Issue by muon-rw** [AlmostReliable/almostunified#78]
### Describe the feature/addition!

Tiered pulls default reforge materials from the repair materials for a piece of gear. If this material is “disabled” by Almost Unified, the reforge recipe does not change, making the gear unreforgeable. 

I assume Almost Unified already fixes repair materials; so this request is to apply the same behavior to tiered’s reforge materials

https://github.com/nvb-uy/Tierify/tree/main

https://www.curseforge.com/minecraft/mc-mods/tierify

### Why would like to see this feature/addition?

While these can be fixed manually with [Tiered’s override recipes](https://github.com/nvb-uy/Tierify/blob/main/src/main/resources/data/tiered/reforge_items/compat_mutantmonsters.json) it can get pretty tedious.

**Comment by rlnt** [comment]
After looking at the mod's source, I think it would be better if integration would be added on their side. Since this is Fabric and 1.20.1 only, it's also not realistic that we will add support on our side in the future since we are focusing on 1.21+.

If they want to add support for unified items in their mod, they should be easily able to do that in their `ReforgeDataLoader` or their main class  `Tierify#registerReforgeItemSyncer` by making use of [the lookup we provide](https://github.com/AlmostReliable/almostunified/wiki/API#create-a-simple-adapter). They would just have to check if the mod is loaded, try to resolve the preferred item for their current item, and then, if it's non-null, use that instead.
