### ISSUE TITLE
Add "wood" to default materials

### ISSUE THREAD

**Issue by fengshuo2004** [AlmostReliable/almostunified#80]
### Describe the feature/addition!

I suggest adding "wood" to the list of materials to unify by default. This would unify everything tagged `forge:dusts/wood`.

In my modpack, this unifies sawdusts added by **Thermal series**, **Immersive Engineering** and **Mekanism** as well as **Ex Compressum** wood chippings.

### Why would like to see this feature/addition?

It would be benefitial to people playing the aforementioned mods (and other mods that add sawdust). Most tech modpacks contain a combination of these mods. It is unlikely to cause any issues.

**Comment by rlnt** [comment]
I am not a fan of adding something like this to the defaults. Saw Dust is often involved in special recipe types and if we don't support a type like that yet, it will break a lot of stuff. We had a case like that pretty recently in the Productive Trees mod that has its own Saw Dust produced by their own Saw Mill.

We also do not plan to add anything to Almost Unified for Minecraft 1.20.1 anymore, only critical bug fixes. And since the system was redesigned a lot in 1.21+ and configs became data-driven, we will not add a separate default config just for Saw Dust.
The mod was not designed to be plug n' play. You can do that but it will not reach its full potential. It should always be configured according to your needs.

The feature request is understandable, please don't take this personally. I am just not a fan of having it as a default from previous experiences.
