### ISSUE TITLE
almostunified makes my mod fail when registering events with the lowest priority subscription

### ISSUE THREAD

**Issue by joe-vettek** [AlmostReliable/almostunified#87]
### Minecraft Version

1.20.1

### Mod Version

forge-1.20.1-0.9.4

### Describe the bug!

This question may not need a screenshot, it is like this.

My mod subscribes to the lowest priority registration event so that I can check BuiltInRegistries.BLOCK when registering to get most of the mod's blocks.
However, after using Almostunified, most of the mod's blocks are not found, although I can find my own.

For example, I can query the Regions Unexplored block in this event, but after installing Almostunified, I can't find it directly. I printed the registry and found that it was not registered at this time.

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by joe-vettek** [comment]
``` 
@SubscribeEvent(priority = EventPriority.LOWEST)
public static void onRegisterForEnd(RegisterEvent event) {
        if (event.getRegistryKey() == Registries.BLOCK) {
for (var block : BuiltInRegistries.BLOCK.entrySet()) {}
}}
```
        
 my code

**Comment by rlnt** [comment]
We are not doing anything in registries. We barely have startup functionality at all, especially in 1.20.1. Which mod are you referring to here? Is it open source?

**Comment by joe-vettek** [comment]
Thanks for your quick reply. I think it was caused by AlmostUnified because I used a binary method to check this problem. I tested each mod one by one. I was also very surprised.

**Comment by joe-vettek** [comment]
https://github.com/joe-vettek/Tea-the-Story/blob/40ac9ebba48fad6d67600a08dd3c5e8ff33128b6/src/main/java/xueluoanping/teastory/ModContent.java#L94

This is the position of the specific code.

<blockquote><img src="https://opengraph.githubassets.com/b5ddc9137b813726c74ce25737376a4dc2a286c77956ff808d43e348efd0099f/joe-vettek/Tea-the-Story" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/joe-vettek/Tea-the-Story/blob/40ac9ebba48fad6d67600a08dd3c5e8ff33128b6/src/main/java/xueluoanping/teastory/ModContent.java">Tea-the-Story/src/main/java/xueluoanping/teastory/ModContent.java at 40ac9ebba48fad6d67600a08dd3c5e8ff33128b6 · joe-vettek/Tea-the-Story</a></strong></div><div>"Tea the Story" is a Chinese mod about tea and rice.  - joe-vettek/Tea-the-Story</div></blockquote>

**Comment by joe-vettek** [comment]
![image](https://github.com/user-attachments/assets/a9745c88-eea0-47d0-aa47-438df1dde665)
I just use and delete this jar file, the registry print result will be completely different.

**Comment by rlnt** [comment]
This probably won't be the answer you want to hear, but I think it's best if you try to find the problem by debugging. I don't have the time capacity to find a broadly described problem that I can't explain where it might be coming from. Additionally, since this is a version that is no longer actively being updated, as we have version 1.21+ to worry about, it is unlikely that I would even have time to look at this problem. I also classify it as a niche problem. Several large modpacks use Almost Unified and so far no compatibility issues with other mods have been reported, especially when it comes to registration. We only have a single startup-related feature which is the `serverOnly` mode. Enabling that stops syncing modification information to the client. We don't register anything, we don't access any registries on startup and we do not change any registry-related behavior in the vanilla game. I am sorry but I don't think I can help you with this.

**Comment by joe-vettek** [comment]
Thanks for your reply, maybe there are some problems with the Forge mechanism here, I wish you good luck with your mod, I also like the value of your mod.
