### ISSUE TITLE
Mod is required on client

### ISSUE THREAD

**Issue by KatNyxion** [AlmostReliable/almostunified#9]
### Describe the feature/addition!

I just installed your new update on my server (1.19-0.1.0) and now it is saying it needs to be on client side as well, Is there possibly a way to make it stay serverside only? I really enjoy what the mod does, but since its still being adjusted a lot, updating it as you update is what I have been doing. I can't really do that anymore if the clients also need to have it lol

Thanks!

### Why would like to see this feature/addition?

Makes it easier to update

**Comment by rlnt** [comment]
Hmm, that might be an issue with the new recipe modification indicator we use. Previously, we adjusted recipe IDs to make it clear that we modified a recipe. This avoids that modified recipes are reported to the original authors in case it causes problems.

Now, we leave the IDs the same because it caused problems in guidebooks and was not a good approach in general. Instead, a little indicator icon is now rendered inside JEI/REI next to the recipe. However, since JEI/REI are rendered client-side, we had to find a way to send the information of whether a recipe was modified to the client. And we now use a dummy recipe to do this.

This may result in the server complaining that the client couldn't process the recipe via the network. We need to investigate. The plan is definitely to support it as a server-only mod (if desired). Thanks for the report.
