### ISSUE TITLE
[1.21.1] Almost Unified latest version does not load world

### ISSUE THREAD

**Issue by Periam** [AlmostReliable/almostunified#98]
### Minecraft Version

1.21.1

### Mod Version

1.21.1-1.2.0

### Describe the bug!

After installing the mod new worlds or previous world does not fully load, the loading process freeze with the 100% world loaded screen.

### Crash Report

N/A

### Log

https://pastebin.com/E1Lq3ieB

### Additions and Modifications

Yes

### Additions and Modifications Description

megacells-4.0.2
ARchitectury-13.0.6-neoforge
almostunified-neoforge-1.21.1-1.20
jei-1.21.1-neoforge-19.0.23
merequester-neoforge-1.21.1-1.1.8
stellaris-1.21-neoforge-1.1.5

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Did you try to make a backup of your world and try to isolate the issue? All changes Almost Unified applies are temporary. Recipes will return to normal when removing the mod. Please try to remove the mod and see if the world loads. And please try if it loads without any other mods.

If it's still stuck after that, try to hold F3 + C for at least 15 seconds. This should force a crash and give some more insights in the log.

**Comment by Periam** [comment]
So, I tried the F3+C , it did not crash the game so I do not have the logs.
I removed almost unified mod and the world loaded.
If I removed the AE2 or Stellaris mod and keep Almost Unified the world loaded.

**Comment by rlnt** [comment]
I can't reproduce this. Does this only happen on existing worlds or new worlds as well?

**Comment by Periam** [comment]
Yes, it is also happening in new worlds.

**Comment by rlnt** [comment]
Would you be able to provide me an export of your instance with the configs? Upload it here as zip please.

**Comment by Periam** [comment]
Here is the file, let me know if something is missing, also I am on your discord, do you want to keep talking there?

[1.21.1 Issue.zip](https://github.com/user-attachments/files/17377696/1.21.1.Issue.zip)

**Comment by rlnt** [comment]
The issue seems to be MegaCells. If you disable the mod, the world loads fine. I couldn't reproduce it on my setup because I only had AE2 and not the add-ons.

I am assuming their decompression service can't handle one of the unified recipes. I will talk to the author about this. We have a channel for that in the AE2 channel because I am also an AE2 add-on dev.

**Comment by Periam** [comment]
Thanks for reviewing the issue... Do you need something else from my end?

**Comment by rlnt** [comment]
No, thank you for the report.

This is a mix of bad recipes/tags within the Stellaris mod and the discovery of this issue by combining Almost Unified with the MegaCells decompression module. The issue isn't caused by Almost Unified but you are not to blame here considering the log doesn't give any evidence. I hope I can resolve this soon by talking to the other devs.

**Comment by rlnt** [comment]
Tracking issues:
https://github.com/st0x0ef/stellaris/issues/38
https://github.com/st0x0ef/stellaris/issues/39
